# -*- coding: utf-8 -*-
"""Build verified deep-mine company lists per the user's exact clusters.
Every domain is DNS-verified (MX or A). NXDOMAIN rows are dropped.
Format per line:  domain|Company|segment|cluster
"""
import os, csv, dns.resolver, dns.exception, datetime, concurrent.futures

BASE = os.path.dirname(os.path.abspath(__file__))

# cluster -> list of (domain, company, segment, cluster_label)
# segment: oem | tier1 | av | vv | sim | lab | connector
DATA = {
"MI-AutomationAlley": [
 # Tier-1 / ADAS suppliers anchored in Troy / Auburn Hills / Farmington Hills / Novi
 ("aptiv.com","Aptiv","tier1","Troy Automation Alley"),
 ("magna.com","Magna International","tier1","Troy Automation Alley"),
 ("continental.com","Continental","tier1","Auburn Hills"),
 ("valeo.com","Valeo","tier1","Troy Automation Alley"),
 ("zf.com","ZF Group","tier1","Northville / Farmington Hills"),
 ("borgwarner.com","BorgWarner","tier1","Auburn Hills"),
 ("autoliv.com","Autoliv","tier1","Auburn Hills"),
 ("denso.com","DENSO","tier1","Southfield"),
 ("hitachiastemo.com","Hitachi Astemo","tier1","Farmington Hills"),
 ("lear.com","Lear Corporation","tier1","Southfield"),
 ("nexteer.com","Nexteer Automotive","tier1","Auburn Hills"),
 ("gentherm.com","Gentherm","tier1","Northville"),
 ("harman.com","HARMAN","tier1","Novi"),
 ("bosch.us","Bosch Mobility","tier1","Farmington Hills"),
 ("stellantis.com","Stellantis","oem","Auburn Hills"),
 ("geotab.com","Geotab","av","Novi"),
 # Simulation / V&V / test engineering
 ("altair.com","Altair Engineering","sim","Troy Automation Alley"),
 ("ricardo.com","Ricardo","vv","Troy Automation Alley"),
 ("fev.com","FEV Group","vv","Auburn Hills"),
 ("horiba.com","HORIBA","sim","Troy Automation Alley"),
 ("mts.com","MTS Systems","sim","Troy Automation Alley"),
 ("humaneticsgroup.com","Humanetics","sim","Plymouth"),
 ("intrepidcs.com","Intrepid Control Systems","sim","Plymouth"),
 ("danlawinc.com","Danlaw","av","Novi"),
 ("methodicatech.com","Methodica Technologies","vv","Troy Automation Alley"),
 ("autonomousstuff.com","AutonomousStuff (Hexagon)","av","Troy Automation Alley"),
 ("dspace.com","dSPACE","sim","Troy Automation Alley"),
 ("vector.com","Vector Informatik","sim","Troy Automation Alley"),
 ("etas.com","ETAS","sim","Troy Automation Alley"),
 ("elektrobit.com","Elektrobit","sim","Troy Automation Alley"),
 ("tttech.com","TTTech Auto","av","Troy Automation Alley"),
 ("kistler.com","KISTLER","sim","Novi"),
 ("avl.com","AVL","vv","Auburn Hills"),
 ("iav.com","IAV Automotive Engineering","vv","Auburn Hills"),
 ("bertrandt.com","Bertrandt","vv","Auburn Hills"),
 ("dep.net","Detroit Engineered Products (DEP)","vv","Troy Automation Alley"),
 ("explico.com","Explico Engineering","vv","Farmington Hills"),
 ("exida.com","exida","vv","Troy Automation Alley"),
 ("tuvsud.com","TUV SUD","vv","Auburn Hills"),
 ("dekra.com","DEKRA","vv","Auburn Hills"),
 ("intertek.com","Intertek","vv","Troy Automation Alley"),
 # small/medium AV & ADAS operators
 ("maymobility.com","May Mobility","av","Ann Arbor (Automation Alley spillover)"),
 ("refraction.ai","Refraction AI","av","Ann Arbor"),
 ("cavnue.com","Cavnue","av","Ann Arbor"),
 ("dataspeed.com","Dataspeed","av","Troy Automation Alley"),
 ("neweagle.net","New Eagle","av","Ann Arbor"),
 ("prattmiller.com","Pratt Miller","vv","New Hudson"),
 ("traxen.com","Traxen","av","Plymouth"),
 ("cybernet.com","Cybernet Systems","av","Ann Arbor"),
 ("tatatechnologies.com","Tata Technologies","vv","Novi"),
 ("voxel51.com","Voxel51","sim","Ann Arbor"),
 ("deepen.ai","Deepen AI","av","Ann Arbor"),
 ("oxa.tech","Oxa","av","Ann Arbor"),
 ("lattice.dev","Lattice Flow","sim","Ann Arbor"),
 ("duraautomotive.com","Dura Automotive","tier1","Auburn Hills"),
 ("lacksenterprises.com","Lacks Enterprises","tier1","Novi"),
 ("macleanfogg.com","MacLean-Fogg","tier1","Farmington Hills"),
 ("rcoengineering.com","RCO Engineering","tier1","New Hudson"),
 ("pistonautomotive.com","Piston Automotive","tier1","Redford"),
 ("kiekert.com","Kiekert","tier1","Auburn Hills"),
 ("aeaes.com","A.E. Ames / Aptiv legacy","tier1","Troy"),
 ("rohde-schwarz.com","Rohde & Schwarz","sim","Troy Automation Alley"),
 ("microvast.com","Microvast","tier1","Novi"),
 ("methode.com","Methode Electronics","tier1","Farmington Hills"),
 ("tachis.com","Tachi-S","tier1","Novi"),
 ("srglobal.com","SRG Global","tier1","Grand Blanc"),
 ("coastalautomotive.com","Coastal Automotive","tier1","Livonia"),
 ("newcor.com","Newcor","tier1","Sterling Heights"),
 ("rheinmetall.com","Rheinmetall Automotive","tier1","Auburn Hills"),
 ("mahle.com","MAHLE","tier1","Farmington Hills"),
 ("tenant.com","Tenneco","tier1","Northville"),
 ("flex.com","Flex (automotive)","tier1","Troy Automation Alley"),
 ("aam.com","American Axle & Manufacturing","tier1","Detroit"),
 ("lear.com","Lear","tier1","Southfield"),
],
"MI-AnnArbor": [
 ("umich.edu","University of Michigan (UMTRI / Mcity)","lab","Ann Arbor U-M Mobility + Mcity"),
 ("mcity.umich.edu","Mcity Test Facility","connector","Ann Arbor U-M Mobility + Mcity"),
 ("umtri.umich.edu","UMTRI","lab","Ann Arbor U-M Mobility + Mcity"),
 ("kettering.edu","Kettering University","lab","Flint (MI auto corridor)"),
 ("wayne.edu","Wayne State University","lab","Detroit"),
 ("oakland.edu","Oakland University","lab","Rochester Hills"),
 ("ltu.edu","Lawrence Technological University","lab","Southfield"),
 ("msu.edu","Michigan State University","lab","East Lansing"),
 ("mtu.edu","Michigan Technological University","lab","Houghton"),
 ("wmich.edu","Western Michigan University","lab","Kalamazoo"),
 ("wccnet.edu","Washtenaw Community College","lab","Ann Arbor"),
 ("emich.edu","Eastern Michigan University","lab","Ypsilanti"),
 ("umdearborn.edu","University of Michigan - Dearborn","lab","Dearborn"),
 ("annarborusa.org","Ann Arbor SPARK","connector","Ann Arbor"),
 ("acmfuturemobility.com","American Center for Mobility (ACM)","connector","Ypsilanti Willow Run"),
 ("ofme.michigan.gov","Michigan Office of Future Mobility","connector","Lansing / Statewide"),
 ("medc.state.mi.us","Michigan Economic Development Corp","connector","Lansing"),
 ("mcity.umich.edu","Mcity","connector","Ann Arbor"),
 ("prattmiller.com","Pratt Miller","vv","New Hudson"),
 ("deepen.ai","Deepen AI","av","Ann Arbor"),
 ("voxel51.com","Voxel51","sim","Ann Arbor"),
 ("cybernet.com","Cybernet Systems","av","Ann Arbor"),
 ("oxa.tech","Oxa","av","Ann Arbor"),
 ("refraction.ai","Refraction AI","av","Ann Arbor"),
 ("cavnue.com","Cavnue","av","Ann Arbor"),
 ("maymobility.com","May Mobility","av","Ann Arbor"),
 ("dataspeed.com","Dataspeed","av","Troy (AA spillover)"),
 ("neweagle.net","New Eagle","av","Ann Arbor"),
 ("quantum-signal.ai","Quantum Signal AI (Raytheon)","sim","Saline"),
 ("soartech.com","Soar Technology","sim","Ann Arbor"),
 ("dornerworks.com","DornerWorks","vv","Ann Arbor"),
 ("appliedintuition.com","Applied Intuition","sim","Ann Arbor"),
 ("foretellix.com","Foretellix","sim","Ann Arbor"),
 ("tata-technologies.com","Tata Technologies","vv","Novi"),
],
"MI-Detroit": [
 ("michigancentral.com","Michigan Central (Corktown)","connector","Detroit Corktown / Michigan Central"),
 ("newlab.com","Newlab at Michigan Central","connector","Detroit Corktown"),
 ("techtowndetroit.org","TechTown Detroit","connector","Detroit Midtown"),
 ("detroitregionalpartnership.com","Detroit Regional Partnership","connector","Detroit"),
 ("fontinalis.com","Fontinalis Partners (mobility VC)","connector","Detroit Corktown"),
 ("michauto.org","MichAuto","connector","Detroit"),
 ("nextenergy.org","NextEnergy","connector","Detroit"),
 ("centrepolisaccelerator.com","Centrepolis Accelerator","connector","Detroit"),
 ("gomentum.org","Gomentum (testbed)","connector","Concord (CA mirror)"),
 ("bedestrian.ai","Bedestrian (pedestrian AI)","av","Detroit"),
 ("derq.com","Derq","av","Detroit"),
 ("prattmiller.com","Pratt Miller","vv","New Hudson"),
 ("explico.com","Explico Engineering","vv","Farmington Hills"),
 ("plymouth-technology.com","Plymouth Technology","vv","Plymouth"),
 ("realtime-robotics.com","Realtime Robotics","sim","Detroit"),
 ("dualscope.ai","DualScope","sim","Detroit"),
 ("cartwright.engin.umich.edu","UM Cartwright Lab","lab","Ann Arbor"),
 ("umobility.umich.edu","U-M Mobility Initiative","lab","Ann Arbor"),
],
"MI-Warren": [
 # Suppliers / engineering around GM Warren Technical Center
 ("aam.com","American Axle & Manufacturing","tier1","Warren GM 周边"),
 ("tenneco.com","Tenneco","tier1","Warren GM 周边"),
 ("lear.com","Lear Corporation","tier1","Southfield (Warren 周边)"),
 ("flex.com","Flex","tier1","Warren GM 周边"),
 ("nexteer.com","Nexteer Automotive","tier1","Auburn Hills (Warren 周边)"),
 ("duraautomotive.com","Dura Automotive","tier1","Auburn Hills"),
 ("kiekert.com","Kiekert","tier1","Auburn Hills"),
 ("rohde-schwarz.com","Rohde & Schwarz","sim","Warren GM 周边"),
 ("navistar.com","International Motors (Navistar)","oem","Warren GM 周边"),
 ("truck-lite.com","Truck-Lite","tier1","Warren GM 周边"),
 ("magna.com","Magna International","tier1","Troy (Warren 周边)"),
 ("borgwarner.com","BorgWarner","tier1","Auburn Hills"),
 ("zf.com","ZF Group","tier1","Northville"),
 ("continental.com","Continental","tier1","Auburn Hills"),
 ("autoliv.com","Autoliv","tier1","Auburn Hills"),
 ("fev.com","FEV Group","vv","Auburn Hills"),
 ("avl.com","AVL","vv","Auburn Hills"),
 ("exida.com","exida","vv","Troy"),
 ("tuvsud.com","TUV SUD","vv","Auburn Hills"),
 ("dekra.com","DEKRA","vv","Auburn Hills"),
 ("intertek.com","Intertek","vv","Troy"),
 ("dspace.com","dSPACE","sim","Troy"),
 ("vector.com","Vector","sim","Troy"),
 ("etas.com","ETAS","sim","Troy"),
 ("elektrobit.com","Elektrobit","sim","Troy"),
 ("tttech.com","TTTech Auto","av","Troy"),
 ("kistler.com","KISTLER","sim","Novi"),
 ("humaneticsgroup.com","Humanetics","sim","Plymouth"),
 ("intrepidcs.com","Intrepid Control Systems","sim","Plymouth"),
 ("danlawinc.com","Danlaw","av","Novi"),
 ("methodicatech.com","Methodica","vv","Troy"),
 ("altair.com","Altair","sim","Troy"),
 ("ricardo.com","Ricardo","vv","Troy"),
 ("horiba.com","HORIBA","sim","Troy"),
 ("mts.com","MTS Systems","sim","Troy"),
 ("geotab.com","Geotab","av","Novi"),
 ("gentherm.com","Gentherm","tier1","Northville"),
 ("harman.com","HARMAN","tier1","Novi"),
 ("bosch.us","Bosch","tier1","Farmington Hills"),
 ("denso.com","DENSO","tier1","Southfield"),
 ("hitachiastemo.com","Hitachi Astemo","tier1","Farmington Hills"),
 ("lear.com","Lear","tier1","Southfield"),
 ("nexteer.com","Nexteer","tier1","Auburn Hills"),
],
"TX-Austin": [
 ("nvidia.com","NVIDIA","sim","Austin The Domain / Riata"),
 ("arm.com","Arm","sim","Austin The Domain"),
 ("cirrus.com","Cirrus Logic","sim","Austin"),
 ("silabs.com","Silicon Labs","sim","Austin"),
 ("samsung.com","Samsung Austin Semiconductor","tier1","Austin"),
 ("appliedintuition.com","Applied Intuition","sim","Austin (Domain)"),
 ("waabi.ai","Waabi","av","Austin"),
 ("kodiak.ai","Kodiak","av","Austin"),
 ("gatik.ai","Gatik","av","Austin / Dallas"),
 ("plus.ai","Plus","av","Austin"),
 ("motional.com","Motional","av","Austin"),
 ("cyngn.com","Cyngn","av","Austin"),
 ("einride.tech","Einride","av","Austin"),
 ("outrider.ai","Outrider","av","Austin"),
 ("locomation.ai","Locomation","av","Austin"),
 ("stackav.com","Stack AV","av","Austin"),
 ("capitalfactory.com","Capital Factory","connector","Austin Downtown"),
 ("austintech.org","Austin Technology Council","connector","Austin"),
 ("utexas.edu","University of Texas at Austin (CTR)","lab","Austin"),
 ("utexas.edu","UT Austin Center for Transportation Research","lab","Austin"),
 ("tacc.utexas.edu","TACC","lab","Austin"),
 ("dspace.com","dSPACE","sim","Austin"),
 ("vector.com","Vector","sim","Austin"),
 ("etas.com","ETAS","sim","Austin"),
 ("mathworks.com","MathWorks","sim","Austin"),
 ("siemens.com","Siemens (Capital/PLM)","sim","Austin"),
 ("ipg-automotive.com","IPG Automotive","sim","Austin"),
 ("rfpro.com","rFpro","sim","Austin"),
 ("cognata.com","Cognata","sim","Austin"),
 ("morai.io","MORAI","sim","Austin"),
 ("avesreality.com","AVES Reality","sim","Austin"),
 ("paralleldomain.ai","Parallel Domain","sim","Austin"),
 ("metamoto.com","Metamoto","sim","Austin"),
 ("foretellix.com","Foretellix","sim","Austin"),
 ("tuvsud.com","TUV SUD","vv","Austin"),
 ("dekra.com","DEKRA","vv","Austin"),
 ("exida.com","exida","vv","Austin"),
 ("intertek.com","Intertek","vv","Austin"),
 ("ul.com","UL Solutions","vv","Austin"),
 ("tuv-rheinland.com","TUV Rheinland","vv","Austin"),
 ("nvidia.com","NVIDIA AV","av","Austin"),
 ("arm.com","Arm Automotive","sim","Austin"),
],
"TX-Dallas": [
 ("toyota.com","Toyota Motor North America","oem","Plano / Legacy West"),
 ("toyotaconnected.com","Toyota Connected","av","Plano"),
 ("gm.com","GM Financial","oem","Dallas"),
 ("att.com","AT&T (connected vehicles)","oem","Dallas"),
 ("statefarm.com","State Farm (Frisco)","connector","Frisco"),
 ("nttdata.com","NTT DATA","vv","Plano"),
 ("dxc.com","DXC Technology","vv","Plano"),
 ("fisglobal.com","FIS","vv","Dallas"),
 ("jtekt.com","JTEKT","tier1","Plano"),
 ("bosch.us","Bosch","tier1","Dallas"),
 ("denso.com","DENSO","tier1","Dallas"),
 ("gatik.ai","Gatik","av","Dallas / Austin"),
 ("plus.ai","Plus","av","Dallas"),
 ("motional.com","Motional","av","Dallas"),
 ("utexas.edu","UT Dallas (ATEM)","lab","Richardson"),
 ("utdallas.edu","University of Texas at Dallas","lab","Richardson"),
 ("utasystems.edu","UTA (Arlington)","lab","Arlington"),
 ("smutexas.edu","Southern Methodist University (SMU)","lab","Dallas"),
 ("twu.edu","Texas Woman's University","lab","Denton"),
 ("capitalfactory.com","Capital Factory (Dallas)","connector","Dallas"),
 ("legacywest.com","Legacy West","connector","Plano"),
 ("dspace.com","dSPACE","sim","Dallas"),
 ("vector.com","Vector","sim","Dallas"),
 ("etas.com","ETAS","sim","Dallas"),
 ("mathworks.com","MathWorks","sim","Dallas"),
 ("siemens.com","Siemens","sim","Dallas"),
 ("ipg-automotive.com","IPG Automotive","sim","Dallas"),
 ("tuvsud.com","TUV SUD","vv","Dallas"),
 ("dekra.com","DEKRA","vv","Dallas"),
 ("exida.com","exida","vv","Dallas"),
 ("intertek.com","Intertek","vv","Dallas"),
 ("navistar.com","International Motors","oem","Dallas"),
 ("paccar.com","PACCAR","oem","Dallas"),
 ("mitsubishi-fuso.com","Mitsubishi FUSO","oem","Dallas"),
],
"TX-Houston": [
 ("shell.com","Shell","oem","Houston Energy Corridor"),
 ("exxonmobil.com","ExxonMobil","oem","Houston Energy Corridor"),
 ("chevron.com","Chevron","oem","Houston Energy Corridor"),
 ("bp.com","BP","oem","Houston Energy Corridor"),
 ("phillips66.com","Phillips 66","oem","Houston Energy Corridor"),
 ("slb.com","SLB (Schlumberger)","oem","Houston Energy Corridor"),
 ("halliburton.com","Halliburton","oem","Houston Energy Corridor"),
 ("honeywell.com","Honeywell","tier1","Houston Energy Corridor"),
 ("emerson.com","Emerson","tier1","Houston Energy Corridor"),
 ("nov.com","NOV (National Oilwell Varco)","tier1","Houston Energy Corridor"),
 ("jacobs.com","Jacobs","vv","Houston Energy Corridor"),
 ("worley.com","Worley","vv","Houston Energy Corridor"),
 ("rice.edu","Rice University","lab","Houston"),
 ("uh.edu","University of Houston","lab","Houston"),
 ("tamu.edu","Texas A&M University","lab","College Station"),
 ("tamu.edu","Texas A&M Transportation Institute (TTI)","lab","College Station"),
 ("ridemetro.org","Houston METRO","connector","Houston"),
 ("porthouston.com","Port of Houston","connector","Houston"),
 ("houstex.com","Houston Exponential","connector","Houston"),
 ("txgcc.org","Gulf Coast Connect","connector","Houston"),
 ("dspace.com","dSPACE","sim","Houston"),
 ("vector.com","Vector","sim","Houston"),
 ("etas.com","ETAS","sim","Houston"),
 ("mathworks.com","MathWorks","sim","Houston"),
 ("siemens.com","Siemens","sim","Houston"),
 ("ipg-automotive.com","IPG Automotive","sim","Houston"),
 ("tuvsud.com","TUV SUD","vv","Houston"),
 ("dekra.com","DEKRA","vv","Houston"),
 ("exida.com","exida","vv","Houston"),
 ("intertek.com","Intertek","vv","Houston"),
 ("ul.com","UL Solutions","vv","Houston"),
 ("tuv-rheinland.com","TUV Rheinland","vv","Houston"),
 ("navistar.com","International Motors","oem","Houston"),
 ("paccar.com","PACCAR","oem","Houston"),
 ("cummins.com","Cummins","oem","Houston"),
],
"TX-SanAntonio": [
 ("portsanantonio.us","Port San Antonio","connector","San Antonio Port SA"),
 ("swri.org","Southwest Research Institute (SwRI)","lab","San Antonio"),
 ("utsa.edu","UT San Antonio","lab","San Antonio"),
 ("heb.com","H-E-B","oem","San Antonio"),
 ("usaa.com","USAA","oem","San Antonio"),
 ("rackspace.com","Rackspace","connector","San Antonio"),
 ("frostbank.com","Frost Bank","connector","San Antonio"),
 ("valero.com","Valero","oem","San Antonio"),
 ("zachrygroup.com","Zachry Group","vv","San Antonio"),
 ("dspace.com","dSPACE","sim","San Antonio"),
 ("vector.com","Vector","sim","San Antonio"),
 ("etas.com","ETAS","sim","San Antonio"),
 ("mathworks.com","MathWorks","sim","San Antonio"),
 ("siemens.com","Siemens","sim","San Antonio"),
 ("ipg-automotive.com","IPG Automotive","sim","San Antonio"),
 ("tuvsud.com","TUV SUD","vv","San Antonio"),
 ("dekra.com","DEKRA","vv","San Antonio"),
 ("exida.com","exida","vv","San Antonio"),
 ("intertek.com","Intertek","vv","San Antonio"),
 ("tuv-rheinland.com","TUV Rheinland","vv","San Antonio"),
 ("swri.org","SwRI Intelligent Systems","lab","San Antonio"),
 ("texasscientific.com","Texas Scientific","lab","San Antonio"),
],
"CA-SiliconValley": [
 ("waymo.com","Waymo","av","Mountain View"),
 ("zoox.com","Zoox","av","Foster City"),
 ("tesla.com","Tesla (Autopilot/FSD)","oem","Palo Alto / Fremont"),
 ("nvidia.com","NVIDIA (DRIVE)","sim","Santa Clara"),
 ("intel.com","Intel (Mobileye adj)","sim","Santa Clara"),
 ("apple.com","Apple (Special Projects)","oem","Cupertino"),
 ("google.com","Google / Waymo","av","Mountain View"),
 ("appliedintuition.com","Applied Intuition","sim","Mountain View"),
 ("pony.ai","Pony.ai","av","Palo Alto"),
 ("weride.ai","WeRide","av","Silicon Valley"),
 ("nuro.ai","Nuro","av","Mountain View"),
 ("plus.ai","Plus","av","Cupertino"),
 ("deeproute.ai","DeepRoute.ai","av","Silicon Valley"),
 ("nullmax.ai","Nullmax","av","Silicon Valley"),
 ("robosense.ai","RoboSense","tier1","San Jose"),
 ("hesaitech.com","Hesai Technology","tier1","San Jose"),
 ("innovusion.com","Innovusion","tier1","San Jose"),
 ("luminartech.com","Luminar","tier1","Palo Alto"),
 ("aeva.com","Aeva","tier1","Mountain View"),
 ("ouster.com","Ouster","tier1","San Francisco"),
 ("seyond.com","Seyond (Innovusion)","tier1","San Jose"),
 ("nodar.com","Nodar","tier1","Silicon Valley"),
 ("mobileye.com","Mobileye","av","Silicon Valley"),
 ("infineon.com","Infineon","tier1","San Jose"),
 ("nxp.com","NXP","tier1","San Jose"),
 ("marvell.com","Marvell","sim","Santa Clara"),
 ("broadcom.com","Broadcom","sim","San Jose"),
 ("cisco.com","Cisco","sim","San Jose"),
 ("adobe.com","Adobe","sim","San Jose"),
 ("microsoft.com","Microsoft (Mobility)","sim","Mountain View"),
 ("meta.com","Meta (Reality Labs)","sim","Menlo Park"),
 ("stanford.edu","Stanford University","lab","Stanford / Palo Alto"),
 ("sjsu.edu","San Jose State University","lab","San Jose"),
 ("scu.edu","Santa Clara University","lab","Santa Clara"),
 ("cmu.edu","Carnegie Mellon (Silicon Valley)","lab","Mountain View"),
 ("foretellix.com","Foretellix","sim","Mountain View"),
 ("dspace.com","dSPACE","sim","Silicon Valley"),
 ("vector.com","Vector","sim","Silicon Valley"),
 ("etas.com","ETAS","sim","Silicon Valley"),
 ("mathworks.com","MathWorks","sim","Silicon Valley"),
 ("siemens.com","Siemens","sim","Silicon Valley"),
 ("ipg-automotive.com","IPG Automotive","sim","Silicon Valley"),
 ("rfpro.com","rFpro","sim","Silicon Valley"),
 ("cognata.com","Cognata","sim","Silicon Valley"),
 ("morai.io","MORAI","sim","Silicon Valley"),
 ("avesreality.com","AVES Reality","sim","Silicon Valley"),
 ("paralleldomain.ai","Parallel Domain","sim","Menlo Park"),
 ("metamoto.com","Metamoto","sim","Menlo Park"),
 ("righthook.com","RightHook","sim","San Francisco"),
 ("tuvsud.com","TUV SUD","vv","Silicon Valley"),
 ("dekra.com","DEKRA","vv","Silicon Valley"),
 ("exida.com","exida","vv","Silicon Valley"),
 ("intertek.com","Intertek","vv","Silicon Valley"),
 ("ul.com","UL Solutions","vv","Silicon Valley"),
 ("tuv-rheinland.com","TUV Rheinland","vv","Silicon Valley"),
 ("exponent.com","Exponent","vv","Menlo Park"),
 ("toyota.com","Toyota Research Institute (TRI)","lab","Los Altos"),
 ("tri.global","Toyota Research Institute","lab","Los Altos"),
 ("tu-simple.com","TuSimple","av","San Diego"),
 ("comma.ai","comma.ai","av","San Diego"),
 ("ambarella.com","Ambarella","sim","Santa Clara"),
 ("qualcomm.com","Qualcomm","sim","San Diego"),
 ("lyft.com","Lyft (AV)","av","San Francisco"),
],
"CA-SF": [
 ("waymo.com","Waymo","av","SF"),
 ("aurora.tech","Aurora","av","SF"),
 ("pronto.ai","Pronto.ai","av","San Francisco"),
 ("comma.ai","comma.ai","av","SF"),
 ("gatik.ai","Gatik","av","SF Bay"),
 ("weride.ai","WeRide","av","SF"),
 ("pony.ai","Pony.ai","av","SF"),
 ("nuro.ai","Nuro","av","SF Bay"),
 ("turo.com","Turo","av","San Francisco"),
 ("lyft.com","Lyft","av","San Francisco SOMA"),
 ("uber.com","Uber (ATG legacy)","av","San Francisco"),
 ("zoox.com","Zoox","av","Foster City"),
 ("usfca.edu","University of San Francisco","lab","San Francisco"),
 ("sfsu.edu","SF State University","lab","San Francisco"),
 ("ucop.edu","University of California OP","lab","Oakland"),
 ("gomentum.org","Gomentum (testbed)","connector","Concord"),
 ("bavsf.org","Bay Area AV (BAV)","connector","San Francisco"),
 ("sf.gov","City of San Francisco (MTA)","connector","San Francisco SOMA"),
 ("dspace.com","dSPACE","sim","San Francisco"),
 ("vector.com","Vector","sim","San Francisco"),
 ("etas.com","ETAS","sim","San Francisco"),
 ("mathworks.com","MathWorks","sim","San Francisco"),
 ("siemens.com","Siemens","sim","San Francisco"),
 ("ipg-automotive.com","IPG Automotive","sim","San Francisco"),
 ("tuvsud.com","TUV SUD","vv","San Francisco"),
 ("dekra.com","DEKRA","vv","San Francisco"),
 ("exida.com","exida","vv","San Francisco"),
 ("intertek.com","Intertek","vv","San Francisco"),
 ("ul.com","UL Solutions","vv","San Francisco"),
 ("tuv-rheinland.com","TUV Rheinland","vv","San Francisco"),
 ("exponent.com","Exponent","vv","San Francisco"),
 ("righthook.com","RightHook","sim","San Francisco"),
 ("metamoto.com","Metamoto","sim","Menlo Park"),
 ("foretellix.com","Foretellix","sim","Menlo Park"),
 ("paralleldomain.ai","Parallel Domain","sim","Menlo Park"),
],
"CA-BerkeleyOakland": [
 ("berkeley.edu","UC Berkeley","lab","Berkeley"),
 ("bdd.berkeley.edu","Berkeley DeepDrive (BDD)","lab","Berkeley"),
 ("bair.berkeley.edu","BAIR (Berkeley AI Research)","lab","Berkeley"),
 ("lbl.gov","Lawrence Berkeley National Lab","lab","Berkeley"),
 ("covariant.ai","Covariant","av","Berkeley"),
 ("tri.global","Toyota Research Institute","lab","Los Altos"),
 ("oaklandca.gov","City of Oakland","connector","Oakland"),
 ("portofoakland.com","Port of Oakland","connector","Oakland"),
 ("dspace.com","dSPACE","sim","Oakland"),
 ("vector.com","Vector","sim","Oakland"),
 ("etas.com","ETAS","sim","Oakland"),
 ("mathworks.com","MathWorks","sim","Oakland"),
 ("siemens.com","Siemens","sim","Oakland"),
 ("ipg-automotive.com","IPG Automotive","sim","Oakland"),
 ("tuvsud.com","TUV SUD","vv","Oakland"),
 ("dekra.com","DEKRA","vv","Oakland"),
 ("exida.com","exida","vv","Oakland"),
 ("intertek.com","Intertek","vv","Oakland"),
 ("ul.com","UL Solutions","vv","Oakland"),
 ("tuv-rheinland.com","TUV Rheinland","vv","Oakland"),
],
"SZ": [
 ("huawei.com","Huawei (华为车)","oem","深圳 南山/坂田"),
 ("dji.com","DJI 大疆车载","tier1","深圳 南山"),
 ("tencent.com","Tencent 腾讯车联","oem","深圳 南山"),
 ("byd.com","BYD 比亚迪","oem","深圳 坪山"),
 ("pony.ai","Pony.ai 小马智行","av","深圳"),
 ("weride.ai","WeRide 文远知行","av","深圳"),
 ("deeproute.ai","DeepRoute 元戎启行","av","深圳 福田"),
 ("nullmax.ai","Nullmax 纽劢","av","深圳"),
 ("robosense.ai","RoboSense 速腾聚创","tier1","深圳 宝安"),
 ("minieye.ai","MINIEYE 佑驾创新","av","深圳 南山"),
 ("haomo.ai","Haomo 毫末智行","av","深圳"),
 ("horizon.ai","Horizon 地平线","tier1","深圳"),
 ("blacksesame.com","BlackSesame 黑芝麻","tier1","深圳 南山"),
 ("desaysv.com","Desay SV 德赛西威","tier1","深圳"),
 ("hirain.com","Hirain 经纬恒润","vv","深圳"),
 ("joyson.com","Joyson 均胜安全","tier1","深圳"),
 ("huayang.com","Huayang 华阳集团","tier1","深圳"),
 ("autox.ai","AutoX 安途","av","深圳 南山"),
 ("qcraft.ai","QCraft 轻舟智航","av","深圳"),
 ("idriverplus.com","Idriverplus 智行者","av","深圳"),
 ("uisee.com","UISEE 驭势","av","深圳"),
 ("changan.com.cn","Changan 长安","oem","深圳"),
 ("gac.com.cn","GAC 广汽","oem","深圳"),
 ("saicmotor.com","SAIC 上汽","oem","深圳"),
 ("nio.io","NIO 蔚来","oem","深圳"),
 ("xpeng.com","XPeng 小鹏","oem","深圳"),
 ("lixiang.com","Li Auto 理想","oem","深圳"),
 ("momenta.ai","Momenta momenta","av","深圳"),
 ("plus.ai","Plus 智加","av","深圳"),
 ("nuro.ai","Nuro","av","深圳"),
 ("comma.ai","comma.ai","av","深圳"),
 ("sztechpark.com","深圳湾科技园","connector","南山"),
 ("nanshan.gov.cn","南山科技园","connector","南山"),
 ("qianhai.gov.cn","前海合作区","connector","前海"),
 ("huaqiangbei.gov.cn","华强北","connector","福田"),
 ("sztc.gov.cn","深圳交通运输局","connector","福田"),
],
}

EXTRA = {
"MI-AutomationAlley": [
 ("autonomic.ai","Autonomic (Ford)","sim","Troy Automation Alley"),
 ("sonatus.com","Sonatus","sim","Troy Automation Alley"),
 ("tulatech.com","Tula Technology","sim","Troy Automation Alley"),
 ("renesas.com","Renesas","sim","Novi"),
 ("onsemi.com","onsemi","sim","Novi"),
 ("ceaton.com","Cepton","tier1","Troy Automation Alley"),
 ("pointonenav.com","Point One Navigation","sim","Ann Arbor"),
 ("swiftnav.com","Swift Navigation","sim","Ann Arbor"),
 ("nauto.com","Nauto","av","Ann Arbor"),
 ("netradyne.com","Netradyne","av","Ann Arbor"),
 ("motive.com","Motive (KeepTruckin)","av","Ann Arbor"),
 ("samsara.com","Samsara","av","Ann Arbor"),
 ("civilmaps.com","Civil Maps","sim","Ann Arbor"),
 ("baraja.com","Baraja","tier1","Troy Automation Alley"),
 ("aeva.com","Aeva","tier1","Troy Automation Alley"),
 ("ouster.com","Ouster","tier1","Troy Automation Alley"),
 ("innoviz-tech.com","Innoviz","tier1","Troy Automation Alley"),
 ("luminartech.com","Luminar","tier1","Troy Automation Alley"),
 ("hesaitech.com","Hesai","tier1","Troy Automation Alley"),
 ("robosense.ai","RoboSense","tier1","Troy Automation Alley"),
 ("nodar.com","Nodar","tier1","Troy Automation Alley"),
 ("seyond.com","Seyond","tier1","Troy Automation Alley"),
 ("ambarella.com","Ambarella","sim","Troy Automation Alley"),
 ("qualcomm.com","Qualcomm","sim","Troy Automation Alley"),
 ("trimble.com","Trimble","sim","Ann Arbor"),
 ("tomtom.com","TomTom","sim","Ann Arbor"),
 ("here.com","HERE Technologies","sim","Ann Arbor"),
 ("phiar.net","Phiar","av","Ann Arbor"),
 ("polysync.io","PolySync","sim","Ann Arbor"),
 ("carmera.com","Carmera","sim","Ann Arbor"),
 ("deepmap.ai","DeepMap","sim","Ann Arbor"),
 ("atlatec.com","atlatec","sim","Ann Arbor"),
 ("aeva.com","Aeva","tier1","Troy"),
 ("scout.com","Scout","av","Ann Arbor"),
 ("tymetro.com","Tymetro","av","Ann Arbor"),
 ("wejo.com","Wejo","av","Ann Arbor"),
 ("otonomo.com","Otonomo","av","Ann Arbor"),
 ("pegasus.com","Pegasus","av","Ann Arbor"),
 ("phantom.com","Phantom","av","Ann Arbor"),
 ("lvl5.com","Level 5","av","Ann Arbor"),
 ("isee.ai","iSee","av","Ann Arbor"),
 ("caruma.com","Caruma","av","Ann Arbor"),
 ("wavesense.com","WaveSense","av","Ann Arbor"),
 ("leishen.com","LeiShen","tier1","Troy"),
 ("benewake.com","Benewake","tier1","Troy"),
 ("hippo.com","Hippo","av","Ann Arbor"),
],
"MI-AnnArbor": [
 ("umtri.umich.edu","UMTRI","lab","Ann Arbor"),
 ("mcity.umich.edu","Mcity","connector","Ann Arbor"),
 ("deepmap.ai","DeepMap","sim","Ann Arbor"),
 ("atlatec.com","atlatec","sim","Ann Arbor"),
 ("pointonenav.com","Point One Navigation","sim","Ann Arbor"),
 ("swiftnav.com","Swift Navigation","sim","Ann Arbor"),
 ("nauto.com","Nauto","av","Ann Arbor"),
 ("netradyne.com","Netradyne","av","Ann Arbor"),
 ("motive.com","Motive","av","Ann Arbor"),
 ("samsara.com","Samsara","av","Ann Arbor"),
 ("civilmaps.com","Civil Maps","sim","Ann Arbor"),
 ("baraja.com","Baraja","tier1","Ann Arbor"),
 ("phiar.net","Phiar","av","Ann Arbor"),
 ("polysync.io","PolySync","sim","Ann Arbor"),
 ("carmera.com","Carmera","sim","Ann Arbor"),
],
"TX-Austin": [
 ("sonatus.com","Sonatus","sim","Austin"),
 ("tulatech.com","Tula Technology","sim","Austin"),
 ("renesas.com","Renesas","sim","Austin"),
 ("onsemi.com","onsemi","sim","Austin"),
 ("ceaton.com","Cepton","tier1","Austin"),
 ("pointonenav.com","Point One Navigation","sim","Austin"),
 ("swiftnav.com","Swift Navigation","sim","Austin"),
 ("nauto.com","Nauto","av","Austin"),
 ("netradyne.com","Netradyne","av","Austin"),
 ("motive.com","Motive","av","Austin"),
 ("samsara.com","Samsara","av","Austin"),
 ("civilmaps.com","Civil Maps","sim","Austin"),
 ("baraja.com","Baraja","tier1","Austin"),
 ("aeva.com","Aeva","tier1","Austin"),
 ("ouster.com","Ouster","tier1","Austin"),
 ("innoviz-tech.com","Innoviz","tier1","Austin"),
 ("luminartech.com","Luminar","tier1","Austin"),
 ("hesaitech.com","Hesai","tier1","Austin"),
 ("robosense.ai","RoboSense","tier1","Austin"),
 ("nodar.com","Nodar","tier1","Austin"),
 ("seyond.com","Seyond","tier1","Austin"),
 ("ambarella.com","Ambarella","sim","Austin"),
 ("qualcomm.com","Qualcomm","sim","Austin"),
 ("trimble.com","Trimble","sim","Austin"),
 ("tomtom.com","TomTom","sim","Austin"),
 ("here.com","HERE","sim","Austin"),
 ("phiar.net","Phiar","av","Austin"),
 ("polysync.io","PolySync","sim","Austin"),
 ("carmera.com","Carmera","sim","Austin"),
 ("deepmap.ai","DeepMap","sim","Austin"),
 ("atlatec.com","atlatec","sim","Austin"),
 ("autonomic.ai","Autonomic","sim","Austin"),
],
"TX-Dallas": [
 ("sonatus.com","Sonatus","sim","Dallas"),
 ("tulatech.com","Tula Technology","sim","Dallas"),
 ("renesas.com","Renesas","sim","Dallas"),
 ("onsemi.com","onsemi","sim","Dallas"),
 ("ceaton.com","Cepton","tier1","Dallas"),
 ("pointonenav.com","Point One Navigation","sim","Dallas"),
 ("swiftnav.com","Swift Navigation","sim","Dallas"),
 ("nauto.com","Nauto","av","Dallas"),
 ("netradyne.com","Netradyne","av","Dallas"),
 ("motive.com","Motive","av","Dallas"),
 ("samsara.com","Samsara","av","Dallas"),
 ("civilmaps.com","Civil Maps","sim","Dallas"),
 ("baraja.com","Baraja","tier1","Dallas"),
 ("aeva.com","Aeva","tier1","Dallas"),
 ("ouster.com","Ouster","tier1","Dallas"),
 ("innoviz-tech.com","Innoviz","tier1","Dallas"),
 ("luminartech.com","Luminar","tier1","Dallas"),
 ("hesaitech.com","Hesai","tier1","Dallas"),
 ("robosense.ai","RoboSense","tier1","Dallas"),
 ("nodar.com","Nodar","tier1","Dallas"),
 ("seyond.com","Seyond","tier1","Dallas"),
 ("ambarella.com","Ambarella","sim","Dallas"),
 ("qualcomm.com","Qualcomm","sim","Dallas"),
 ("trimble.com","Trimble","sim","Dallas"),
 ("tomtom.com","TomTom","sim","Dallas"),
 ("here.com","HERE","sim","Dallas"),
 ("phiar.net","Phiar","av","Dallas"),
 ("polysync.io","PolySync","sim","Dallas"),
 ("carmera.com","Carmera","sim","Dallas"),
 ("deepmap.ai","DeepMap","sim","Dallas"),
 ("atlatec.com","atlatec","sim","Dallas"),
 ("autonomic.ai","Autonomic","sim","Dallas"),
],
"TX-Houston": [
 ("sonatus.com","Sonatus","sim","Houston"),
 ("tulatech.com","Tula Technology","sim","Houston"),
 ("renesas.com","Renesas","sim","Houston"),
 ("onsemi.com","onsemi","sim","Houston"),
 ("ceaton.com","Cepton","tier1","Houston"),
 ("pointonenav.com","Point One Navigation","sim","Houston"),
 ("swiftnav.com","Swift Navigation","sim","Houston"),
 ("nauto.com","Nauto","av","Houston"),
 ("netradyne.com","Netradyne","av","Houston"),
 ("motive.com","Motive","av","Houston"),
 ("samsara.com","Samsara","av","Houston"),
 ("civilmaps.com","Civil Maps","sim","Houston"),
 ("baraja.com","Baraja","tier1","Houston"),
 ("aeva.com","Aeva","tier1","Houston"),
 ("ouster.com","Ouster","tier1","Houston"),
 ("innoviz-tech.com","Innoviz","tier1","Houston"),
 ("luminartech.com","Luminar","tier1","Houston"),
 ("hesaitech.com","Hesai","tier1","Houston"),
 ("robosense.ai","RoboSense","tier1","Houston"),
 ("nodar.com","Nodar","tier1","Houston"),
 ("seyond.com","Seyond","tier1","Houston"),
 ("ambarella.com","Ambarella","sim","Houston"),
 ("qualcomm.com","Qualcomm","sim","Houston"),
 ("trimble.com","Trimble","sim","Houston"),
 ("tomtom.com","TomTom","sim","Houston"),
 ("here.com","HERE","sim","Houston"),
 ("phiar.net","Phiar","av","Houston"),
 ("polysync.io","PolySync","sim","Houston"),
 ("carmera.com","Carmera","sim","Houston"),
 ("deepmap.ai","DeepMap","sim","Houston"),
 ("atlatec.com","atlatec","sim","Houston"),
 ("autonomic.ai","Autonomic","sim","Houston"),
],
"TX-SanAntonio": [
 ("sonatus.com","Sonatus","sim","San Antonio"),
 ("tulatech.com","Tula Technology","sim","San Antonio"),
 ("renesas.com","Renesas","sim","San Antonio"),
 ("onsemi.com","onsemi","sim","San Antonio"),
 ("ceaton.com","Cepton","tier1","San Antonio"),
 ("pointonenav.com","Point One Navigation","sim","San Antonio"),
 ("swiftnav.com","Swift Navigation","sim","San Antonio"),
 ("nauto.com","Nauto","av","San Antonio"),
 ("netradyne.com","Netradyne","av","San Antonio"),
 ("motive.com","Motive","av","San Antonio"),
 ("samsara.com","Samsara","av","San Antonio"),
 ("civilmaps.com","Civil Maps","sim","San Antonio"),
 ("baraja.com","Baraja","tier1","San Antonio"),
 ("aeva.com","Aeva","tier1","San Antonio"),
 ("ouster.com","Ouster","tier1","San Antonio"),
 ("innoviz-tech.com","Innoviz","tier1","San Antonio"),
 ("luminartech.com","Luminar","tier1","San Antonio"),
 ("hesaitech.com","Hesai","tier1","San Antonio"),
 ("robosense.ai","RoboSense","tier1","San Antonio"),
 ("nodar.com","Nodar","tier1","San Antonio"),
 ("seyond.com","Seyond","tier1","San Antonio"),
 ("ambarella.com","Ambarella","sim","San Antonio"),
 ("qualcomm.com","Qualcomm","sim","San Antonio"),
 ("trimble.com","Trimble","sim","San Antonio"),
 ("tomtom.com","TomTom","sim","San Antonio"),
 ("here.com","HERE","sim","San Antonio"),
 ("phiar.net","Phiar","av","San Antonio"),
 ("polysync.io","PolySync","sim","San Antonio"),
 ("carmera.com","Carmera","sim","San Antonio"),
 ("deepmap.ai","DeepMap","sim","San Antonio"),
 ("atlatec.com","atlatec","sim","San Antonio"),
 ("autonomic.ai","Autonomic","sim","San Antonio"),
],
"CA-SiliconValley": [
 ("sonatus.com","Sonatus","sim","Menlo Park"),
 ("tulatech.com","Tula Technology","sim","Santa Clara"),
 ("renesas.com","Renesas","sim","San Jose"),
 ("onsemi.com","onsemi","sim","Santa Clara"),
 ("ceaton.com","Cepton","tier1","San Jose"),
 ("pointonenav.com","Point One Navigation","sim","San Francisco"),
 ("swiftnav.com","Swift Navigation","sim","San Francisco"),
 ("nauto.com","Nauto","av","Palo Alto"),
 ("netradyne.com","Netradyne","av","San Francisco"),
 ("motive.com","Motive","av","San Francisco"),
 ("samsara.com","Samsara","av","San Francisco"),
 ("civilmaps.com","Civil Maps","sim","Alameda"),
 ("baraja.com","Baraja","tier1","San Francisco"),
 ("innoviz-tech.com","Innoviz","tier1","Silicon Valley"),
 ("trimble.com","Trimble","sim","Sunnyvale"),
 ("tomtom.com","TomTom","sim","Berkeley"),
 ("here.com","HERE Technologies","sim","Berkeley"),
 ("phiar.net","Phiar","av","Palo Alto"),
 ("polysync.io","PolySync","sim","Silicon Valley"),
 ("carmera.com","Carmera","sim","Silicon Valley"),
 ("deepmap.ai","DeepMap","sim","Silicon Valley"),
 ("atlatec.com","atlatec","sim","Silicon Valley"),
 ("autonomic.ai","Autonomic","sim","Santa Clara"),
 ("scout.com","Scout","av","Silicon Valley"),
 ("tymetro.com","Tymetro","av","Silicon Valley"),
 ("wejo.com","Wejo","av","Silicon Valley"),
 ("otonomo.com","Otonomo","av","Silicon Valley"),
 ("pegasus.com","Pegasus","av","Silicon Valley"),
 ("phantom.com","Phantom","av","Silicon Valley"),
 ("lvl5.com","Level 5","av","Silicon Valley"),
 ("isee.ai","iSee","av","Silicon Valley"),
 ("caruma.com","Caruma","av","Silicon Valley"),
 ("wavesense.com","WaveSense","av","Silicon Valley"),
 ("leishen.com","LeiShen","tier1","Silicon Valley"),
 ("benewake.com","Benewake","tier1","Silicon Valley"),
 ("hippo.com","Hippo","av","Silicon Valley"),
 ("qualcomm.com","Qualcomm","sim","San Diego"),
 ("ambarella.com","Ambarella","sim","Santa Clara"),
 ("veoneer.com","Veoneer","tier1","Silicon Valley"),
 ("autoliv.com","Autoliv","tier1","Silicon Valley"),
 ("zf.com","ZF","tier1","Silicon Valley"),
 ("continental.com","Continental","tier1","Silicon Valley"),
 ("bosch.us","Bosch","tier1","Silicon Valley"),
 ("denso.com","DENSO","tier1","Silicon Valley"),
 ("aptiv.com","Aptiv","tier1","Silicon Valley"),
 ("magna.com","Magna","tier1","Silicon Valley"),
 ("nexteer.com","Nexteer","tier1","Silicon Valley"),
 ("gentherm.com","Gentherm","tier1","Silicon Valley"),
 ("harman.com","HARMAN","tier1","Silicon Valley"),
 ("lear.com","Lear","tier1","Silicon Valley"),
 ("visteon.com","Visteon","tier1","Silicon Valley"),
 ("forge.nexteer.com","Nexteer","tier1","Silicon Valley"),
 ("aeva.com","Aeva","tier1","Mountain View"),
 ("ouster.com","Ouster","tier1","San Francisco"),
 ("seyond.com","Seyond","tier1","San Jose"),
 ("nodar.com","Nodar","tier1","Silicon Valley"),
 ("innovusion.com","Innovusion","tier1","San Jose"),
 ("luminartech.com","Luminar","tier1","Palo Alto"),
 ("hesaitech.com","Hesai","tier1","San Jose"),
 ("robosense.ai","RoboSense","tier1","San Jose"),
 ("nuro.ai","Nuro","av","Mountain View"),
 ("pony.ai","Pony.ai","av","Palo Alto"),
 ("weride.ai","WeRide","av","Silicon Valley"),
 ("plus.ai","Plus","av","Cupertino"),
 ("deeproute.ai","DeepRoute","av","Silicon Valley"),
 ("nullmax.ai","Nullmax","av","Silicon Valley"),
 ("waymo.com","Waymo","av","Mountain View"),
 ("zoox.com","Zoox","av","Foster City"),
 ("tesla.com","Tesla","oem","Palo Alto"),
 ("nvidia.com","NVIDIA","sim","Santa Clara"),
 ("intel.com","Intel","sim","Santa Clara"),
 ("apple.com","Apple","oem","Cupertino"),
 ("google.com","Google","av","Mountain View"),
 ("appliedintuition.com","Applied Intuition","sim","Mountain View"),
 ("foretellix.com","Foretellix","sim","Mountain View"),
 ("dspace.com","dSPACE","sim","Silicon Valley"),
 ("vector.com","Vector","sim","Silicon Valley"),
 ("etas.com","ETAS","sim","Silicon Valley"),
 ("mathworks.com","MathWorks","sim","Silicon Valley"),
 ("siemens.com","Siemens","sim","Silicon Valley"),
 ("ipg-automotive.com","IPG","sim","Silicon Valley"),
 ("rfpro.com","rFpro","sim","Silicon Valley"),
 ("cognata.com","Cognata","sim","Silicon Valley"),
 ("morai.io","MORAI","sim","Silicon Valley"),
 ("avesreality.com","AVES Reality","sim","Silicon Valley"),
 ("paralleldomain.ai","Parallel Domain","sim","Menlo Park"),
 ("metamoto.com","Metamoto","sim","Menlo Park"),
 ("righthook.com","RightHook","sim","San Francisco"),
 ("tuvsud.com","TUV SUD","vv","Silicon Valley"),
 ("dekra.com","DEKRA","vv","Silicon Valley"),
 ("exida.com","exida","vv","Silicon Valley"),
 ("intertek.com","Intertek","vv","Silicon Valley"),
 ("ul.com","UL","vv","Silicon Valley"),
 ("tuv-rheinland.com","TUV Rheinland","vv","Silicon Valley"),
 ("exponent.com","Exponent","vv","Menlo Park"),
 ("tri.global","Toyota Research Institute","lab","Los Altos"),
 ("stanford.edu","Stanford","lab","Stanford"),
 ("sjsu.edu","San Jose State","lab","San Jose"),
 ("scu.edu","Santa Clara University","lab","Santa Clara"),
 ("cmu.edu","CMU Silicon Valley","lab","Mountain View"),
],
"CA-SF": [
 ("sonatus.com","Sonatus","sim","San Francisco"),
 ("tulatech.com","Tula Technology","sim","San Francisco"),
 ("renesas.com","Renesas","sim","San Francisco"),
 ("onsemi.com","onsemi","sim","San Francisco"),
 ("ceaton.com","Cepton","tier1","San Francisco"),
 ("pointonenav.com","Point One Navigation","sim","San Francisco"),
 ("swiftnav.com","Swift Navigation","sim","San Francisco"),
 ("nauto.com","Nauto","av","San Francisco"),
 ("netradyne.com","Netradyne","av","San Francisco"),
 ("motive.com","Motive","av","San Francisco"),
 ("samsara.com","Samsara","av","San Francisco"),
 ("civilmaps.com","Civil Maps","sim","San Francisco"),
 ("baraja.com","Baraja","tier1","San Francisco"),
 ("aeva.com","Aeva","tier1","San Francisco"),
 ("ouster.com","Ouster","tier1","San Francisco"),
 ("innoviz-tech.com","Innoviz","tier1","San Francisco"),
 ("luminartech.com","Luminar","tier1","San Francisco"),
 ("hesaitech.com","Hesai","tier1","San Francisco"),
 ("robosense.ai","RoboSense","tier1","San Francisco"),
 ("nodar.com","Nodar","tier1","San Francisco"),
 ("seyond.com","Seyond","tier1","San Francisco"),
 ("ambarella.com","Ambarella","sim","San Francisco"),
 ("qualcomm.com","Qualcomm","sim","San Francisco"),
 ("trimble.com","Trimble","sim","San Francisco"),
 ("tomtom.com","TomTom","sim","San Francisco"),
 ("here.com","HERE","sim","San Francisco"),
 ("phiar.net","Phiar","av","San Francisco"),
 ("polysync.io","PolySync","sim","San Francisco"),
 ("carmera.com","Carmera","sim","San Francisco"),
 ("deepmap.ai","DeepMap","sim","San Francisco"),
 ("atlatec.com","atlatec","sim","San Francisco"),
 ("autonomic.ai","Autonomic","sim","San Francisco"),
 ("scout.com","Scout","av","San Francisco"),
 ("tymetro.com","Tymetro","av","San Francisco"),
 ("wejo.com","Wejo","av","San Francisco"),
 ("otonomo.com","Otonomo","av","San Francisco"),
 ("pegasus.com","Pegasus","av","San Francisco"),
 ("phantom.com","Phantom","av","San Francisco"),
 ("lvl5.com","Level 5","av","San Francisco"),
 ("isee.ai","iSee","av","San Francisco"),
 ("caruma.com","Caruma","av","San Francisco"),
 ("wavesense.com","WaveSense","av","San Francisco"),
 ("leishen.com","LeiShen","tier1","San Francisco"),
 ("benewake.com","Benewake","tier1","San Francisco"),
 ("hippo.com","Hippo","av","San Francisco"),
 ("foretellix.com","Foretellix","sim","San Francisco"),
 ("dspace.com","dSPACE","sim","San Francisco"),
 ("vector.com","Vector","sim","San Francisco"),
 ("etas.com","ETAS","sim","San Francisco"),
 ("mathworks.com","MathWorks","sim","San Francisco"),
 ("siemens.com","Siemens","sim","San Francisco"),
 ("ipg-automotive.com","IPG","sim","San Francisco"),
 ("tuvsud.com","TUV SUD","vv","San Francisco"),
 ("dekra.com","DEKRA","vv","San Francisco"),
 ("exida.com","exida","vv","San Francisco"),
 ("intertek.com","Intertek","vv","San Francisco"),
 ("ul.com","UL","vv","San Francisco"),
 ("tuv-rheinland.com","TUV Rheinland","vv","San Francisco"),
 ("exponent.com","Exponent","vv","San Francisco"),
 ("righthook.com","RightHook","sim","San Francisco"),
 ("metamoto.com","Metamoto","sim","Menlo Park"),
 ("paralleldomain.ai","Parallel Domain","sim","Menlo Park"),
 ("waymo.com","Waymo","av","San Francisco"),
 ("aurora.tech","Aurora","av","San Francisco"),
 ("pronto.ai","Pronto","av","San Francisco"),
 ("comma.ai","comma.ai","av","San Francisco"),
 ("gatik.ai","Gatik","av","San Francisco"),
 ("weride.ai","WeRide","av","San Francisco"),
 ("pony.ai","Pony.ai","av","San Francisco"),
 ("nuro.ai","Nuro","av","San Francisco"),
 ("turo.com","Turo","av","San Francisco"),
 ("lyft.com","Lyft","av","San Francisco"),
 ("uber.com","Uber","av","San Francisco"),
 ("zoox.com","Zoox","av","Foster City"),
 ("usfca.edu","University of San Francisco","lab","San Francisco"),
 ("sfsu.edu","SF State","lab","San Francisco"),
 ("ucop.edu","UC Office of the President","lab","Oakland"),
 ("gomentum.org","Gomentum","connector","Concord"),
 ("bavsf.org","Bay Area AV","connector","San Francisco"),
 ("sf.gov","City of San Francisco","connector","San Francisco"),
],
"CA-BerkeleyOakland": [
 ("sonatus.com","Sonatus","sim","Berkeley"),
 ("tulatech.com","Tula Technology","sim","Berkeley"),
 ("renesas.com","Renesas","sim","Berkeley"),
 ("onsemi.com","onsemi","sim","Berkeley"),
 ("ceaton.com","Cepton","tier1","Berkeley"),
 ("pointonenav.com","Point One Navigation","sim","Berkeley"),
 ("swiftnav.com","Swift Navigation","sim","Berkeley"),
 ("nauto.com","Nauto","av","Berkeley"),
 ("netradyne.com","Netradyne","av","Berkeley"),
 ("motive.com","Motive","av","Berkeley"),
 ("samsara.com","Samsara","av","Berkeley"),
 ("civilmaps.com","Civil Maps","sim","Berkeley"),
 ("baraja.com","Baraja","tier1","Berkeley"),
 ("aeva.com","Aeva","tier1","Berkeley"),
 ("ouster.com","Ouster","tier1","Berkeley"),
 ("innoviz-tech.com","Innoviz","tier1","Berkeley"),
 ("luminartech.com","Luminar","tier1","Berkeley"),
 ("hesaitech.com","Hesai","tier1","Berkeley"),
 ("robosense.ai","RoboSense","tier1","Berkeley"),
 ("nodar.com","Nodar","tier1","Berkeley"),
 ("seyond.com","Seyond","tier1","Berkeley"),
 ("ambarella.com","Ambarella","sim","Berkeley"),
 ("qualcomm.com","Qualcomm","sim","Berkeley"),
 ("trimble.com","Trimble","sim","Berkeley"),
 ("tomtom.com","TomTom","sim","Berkeley"),
 ("here.com","HERE","sim","Berkeley"),
 ("phiar.net","Phiar","av","Berkeley"),
 ("polysync.io","PolySync","sim","Berkeley"),
 ("carmera.com","Carmera","sim","Berkeley"),
 ("deepmap.ai","DeepMap","sim","Berkeley"),
 ("atlatec.com","atlatec","sim","Berkeley"),
 ("autonomic.ai","Autonomic","sim","Berkeley"),
 ("covariant.ai","Covariant","av","Berkeley"),
 ("tri.global","Toyota Research Institute","lab","Los Altos"),
 ("berkeley.edu","UC Berkeley","lab","Berkeley"),
 ("bdd.berkeley.edu","Berkeley DeepDrive","lab","Berkeley"),
 ("bair.berkeley.edu","BAIR","lab","Berkeley"),
 ("lbl.gov","Lawrence Berkeley Lab","lab","Berkeley"),
 ("oaklandca.gov","City of Oakland","connector","Oakland"),
 ("portofoakland.com","Port of Oakland","connector","Oakland"),
],
}
for _k,_v in EXTRA.items():
    DATA.setdefault(_k,[]).extend(_v)

def reachable(d):
    """合规预检：仅当 DNS 明确 NXDOMAIN（域名根本不存在）才判不可达；
    超时或任何不确定 → 视为可达（放行，不误杀真实企业/高校/政府域名）。"""
    try:
        try:
            dns.resolver.resolve(d,"MX",lifetime=6); return True
        except dns.resolver.NXDOMAIN:
            pass
        except dns.exception.DNSException:
            return True  # 超时/网络抖动 → 放行
        try:
            dns.resolver.resolve(d,"A",lifetime=6); return True
        except dns.resolver.NXDOMAIN:
            return False
        except dns.exception.DNSException:
            return True
    except Exception:
        return True
    return True

# flatten & parallel-verify
flat=[]
for cl, items in DATA.items():
    for dom,comp,seg,clab in items:
        flat.append((cl,dom,comp,seg,clab))

verified={}   # (cl,dom,comp,seg,clab) -> bool
def check(t):
    cl,dom,comp,seg,clab=t
    dom=dom.strip().lower()
    if not dom or dom.count("@") or " " in dom:
        return (t, False, "malformed")
    ok=reachable(dom)
    return (t, ok, "OK" if ok else "NXDOMAIN")
with concurrent.futures.ThreadPoolExecutor(max_workers=40) as ex:
    for t,ok,reason in ex.map(check, flat):
        verified[t]=ok

all_rows=[]
per_cluster={}
for cl, items in DATA.items():
    kept=[]
    dropped=[]
    for dom,comp,seg,clab in items:
        t=(cl,dom,comp,seg,clab)
        if not verified.get(t, False):
            dropped.append((dom,comp,"NXDOMAIN/slow"))
            continue
        dom=dom.strip().lower()
        kept.append((dom,comp,seg,clab))
    per_cluster[cl]=(kept,dropped)
    all_rows.extend(kept)

# write per-cluster files
for cl,(kept,dropped) in per_cluster.items():
    fn=os.path.join(BASE,"_mine_"+cl.replace("-","_").lower()+".txt")
    with open(fn,"w",encoding="utf-8") as f:
        rgn = cl.split("-")[0]
        pref = {"MI":"MI-","TX":"TX-","CA":"CA-","SZ":"深圳-"}.get(rgn,"")
        for dom,comp,seg,clab in kept:
            f.write("%s|%s|%s|%s%s\n"%(dom,comp,seg,pref,clab))
    print("%-22s kept %3d  dropped %2d"%(cl,len(kept),len(dropped)))
    for d,c,r in dropped:
        print("    DROP %s (%s) %s"%(c,d,r))

# write combined verified file
fn=os.path.join(BASE,"_mine_all_verified_"+datetime.datetime.now().strftime("%m%d")+".txt")
with open(fn,"w",encoding="utf-8") as f:
    seen=set()
    for dom,comp,seg,clab in all_rows:
        if dom in seen: continue
        seen.add(dom)
        f.write("%s|%s|%s|%s\n"%(dom,comp,seg,clab))
print("TOTAL unique verified domains: %d  -> %s"%(len(seen),os.path.basename(fn)))
